// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgzhusaqpqhxpexkkgnx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtnemh1c2FxcHFoeHBleGtrZ254Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MTQxMTksImV4cCI6MjA3MjI5MDExOX0.k_sjZnlaiwoM889IJZ_EF6hnvTypLDWWpx7BTexXNEQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});